/**
 * 
 */
package net.sf.cotelab.playingcards.lbl.model;

import static org.junit.Assert.*;
import org.junit.Test;

/**
 * @author US80653H
 *
 */
public class FanTest {
	@Test
	public void test() {
		// there really is no need to test this beast, because the source code
		// is standard delegate-pattern code generated by Eclipse.
		assertTrue(true);
	}
}
